import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import Hydrate from './components/Hydrate'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<Hydrate>
				<body
					className={`flex min-h-screen flex-col items-center between ${inter.className}`}
				>
					<Nav />
					{children}
				</body>
			</Hydrate>
		</html>
	)
}
